### ISSUE TITLE
g_Log_Id not set in LOGGER Package Body

### ISSUE THREAD

**Issue by ngmcfarland** [OraOpenSource/Logger#99] opened 2015-04-15 17:41 UTC
Using Logger 2.1.2:

When trying to use logger.log_apex_items, we kept getting an error in the APEX application stating that "LOG_ID cannot be null". After digging into the logger package body, I see that log_apex_items calls first to log_internal and then to snapshot_apex_items. The problem was occurring during snapshot_apex_items because the variable "g_Log_Id" was not given a value in log_internal. Log_internal calls to ins_logger_logs where the log id is obtained, but then log_internal never passes that log id back out to log_apex_items. To get around this, I created a "l_log_id" within log_apex_items and then added/changed the following lines within log_apex_items:

$IF $$APEX $THEN
          log_internal(
            p_text                => p_text,
            p_log_level            => logger.g_apex,
            p_scope             => p_scope);

          select logger_logs_seq.currval
          into l_log_id
          from dual;

          snapshot_apex_items(p_log_id => l_log_id);

**Comment by martindsouza** [comment] 2015-04-16 12:42
Duplicate of #52. Fixed in 3.0.0 (currently in EA1 but will be released very soon)

**Closed by martindsouza** 2015-04-16 12:42 UTC
Labels: bug, duplicate
